/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'payload-preferences': PayloadPreference;
    articles: Article;
    'article-series': ArticleSery;
    categories: Category;
    subcategories: Subcategory;
    tags: Tag;
    media: Media;
    mediaTracks: MediaTrack;
    albums: Album;
    charts: Chart;
    'chart-snapshots': ChartSnapshot;
    vod: Vod;
    radioShows: RadioShow;
    radioSchedule: RadioSchedule;
    podcasts: Podcast;
    episodes: Episode;
    playlists: Playlist;
    talent: Talent;
    polls: Poll;
    pollVotes: PollVote;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'article-series': ArticleSeriesSelect<false> | ArticleSeriesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    subcategories: SubcategoriesSelect<false> | SubcategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    mediaTracks: MediaTracksSelect<false> | MediaTracksSelect<true>;
    albums: AlbumsSelect<false> | AlbumsSelect<true>;
    charts: ChartsSelect<false> | ChartsSelect<true>;
    'chart-snapshots': ChartSnapshotsSelect<false> | ChartSnapshotsSelect<true>;
    vod: VodSelect<false> | VodSelect<true>;
    radioShows: RadioShowsSelect<false> | RadioShowsSelect<true>;
    radioSchedule: RadioScheduleSelect<false> | RadioScheduleSelect<true>;
    podcasts: PodcastsSelect<false> | PodcastsSelect<true>;
    episodes: EpisodesSelect<false> | EpisodesSelect<true>;
    playlists: PlaylistsSelect<false> | PlaylistsSelect<true>;
    talent: TalentSelect<false> | TalentSelect<true>;
    polls: PollsSelect<false> | PollsSelect<true>;
    pollVotes: PollVotesSelect<false> | PollVotesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'editor' | 'talent' | 'creator' | 'listener')[];
  /**
   * Public-facing name used across the platform.
   */
  displayName?: string | null;
  /**
   * Square image recommended. Used for profile and bylines.
   */
  avatar?: (number | null) | Media;
  subscription?: ('free' | 'premium') | null;
  creatorProfile?: {
    /**
     * Email used for creator payouts.
     */
    payoutEmail?: string | null;
    bio?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Images, audio, and video assets used across WaveNation platforms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  credit?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  subtitle?: string | null;
  /**
   * Auto-generated from title. Do not change after publish.
   */
  slug: string;
  /**
   * Primary editorial categories for this article.
   */
  categories?: (number | Category)[] | null;
  /**
   * Related subcategories for secondary classification and discovery.
   */
  subcategories?: (number | Subcategory)[] | null;
  /**
   * Keywords for SEO, discovery, playlists, and recommendations.
   */
  tags?: (number | Tag)[] | null;
  /**
   * Public publish date. Can be manually overridden. Auto-set on first publish if empty.
   */
  publishDate?: string | null;
  /**
   * Automatically publishes this article at the scheduled time.
   */
  scheduledPublishAt?: string | null;
  status?: ('draft' | 'in-review' | 'approved' | 'published' | 'unpublished' | 'archived') | null;
  reviewTier?: ('tier1' | 'tier2' | 'tier3' | 'tier4') | null;
  /**
   * Marks this article as breaking news. Triggers AI ranking boosts and high-priority placement.
   */
  isBreaking?: boolean | null;
  /**
   * Displays this article in the Spotlight section below the homepage hero.
   */
  isFeatured?: boolean | null;
  author: number | User;
  editorPreset?: ('interview' | 'review' | 'news') | null;
  /**
   * Internal notes explaining significant editorial changes. Not public.
   */
  editorialNotes?:
    | {
        noteType: 'correction' | 'update' | 'breaking-update' | 'seo' | 'legal' | 'review' | 'internal';
        note: string;
        author?: (number | null) | User;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  excerpt?: string | null;
  /**
   * Primary sources used in reporting this article. Required for news, investigations, and fact-based reporting.
   */
  sources?:
    | {
        sourceType: 'news' | 'interview' | 'press' | 'government' | 'research' | 'statement' | 'other';
        title: string;
        /**
         * Outlet, organization, or institution name.
         */
        publication?: string | null;
        /**
         * Link to the original source.
         */
        url?: string | null;
        author?: string | null;
        publishedDate?: string | null;
        /**
         * Marks this as a primary source for the article.
         */
        isPrimary?: boolean | null;
        /**
         * Internal notes about how this source was used.
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Supporting references, documents, archives, or background materials.
   */
  references?:
    | {
        label: string;
        referenceType?: ('law' | 'court' | 'academic' | 'book' | 'archive' | 'media' | 'web' | 'other') | null;
        url?: string | null;
        /**
         * Optional context for editors or AI.
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional series this article belongs to.
   */
  series?: (number | null) | ArticleSery;
  /**
   * Link this article to a WaveNation radio, TV, or podcast show.
   */
  relatedShow?: (number | null) | RadioShow;
  /**
   * Link this article to a WaveNation radio, TV, or podcast show.
   */
  relatedPosdcast?: (number | null) | Podcast;
  /**
   * Link this article to a WaveNation radio, TV, or podcast show.
   */
  relatedVOD?: (number | null) | Vod;
  /**
   * Optional album related to this article (featured release, review, or spotlight).
   */
  relatedAlbum?: (number | null) | Album;
  /**
   * Attach relevant polls to this article
   */
  relatedPolls?: (number | Poll)[] | null;
  menuFeature?: boolean | null;
  menuContext?: ('discover' | 'on-air' | 'news' | 'watch' | 'merch' | 'connect') | null;
  menuEyebrow?: string | null;
  menuDescription?: string | null;
  /**
   * Estimated reading time in minutes (auto-calculated from rich text blocks).
   */
  readingTime?: number | null;
  hero?: {
    image?: (number | null) | Media;
    caption?: string | null;
    credit?: string | null;
  };
  contentBlocks: (
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        /**
         * The interviewer’s question.
         */
        question: string;
        /**
         * Optional interviewer name or role.
         */
        askedBy?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'interviewQuestion';
      }
    | {
        /**
         * The interviewee’s response.
         */
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Interviewee name (useful for multi-guest interviews).
         */
        answeredBy?: string | null;
        /**
         * Mark this answer as a highlight for pull quotes or summaries.
         */
        highlight?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'interviewAnswer';
      }
    | {
        image: number | Media;
        caption?: string | null;
        credit?: string | null;
        fullWidth?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
    | {
        images?:
          | {
              image: number | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        quote: string;
        attribution?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pullQuote';
      }
    | {
        provider: 'youtube' | 'vimeo' | 'upload';
        url?: string | null;
        file?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'video';
      }
    | {
        title?: string | null;
        audioFile: number | Media;
        showName?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'audio';
      }
    | {
        provider?: ('youtube' | 'instagram' | 'tiktok' | 'twitter' | 'other') | null;
        embedUrl: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'embed';
      }
    | {
        artistName: string;
        image?: (number | null) | Media;
        description?: string | null;
        links?:
          | {
              label?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'artistSpotlight';
      }
    | {
        articles?: (number | Article)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'relatedArticles';
      }
    | {
        headline: string;
        body?: string | null;
        buttonLabel?: string | null;
        buttonUrl?: string | null;
        variant?: ('primary' | 'secondary' | 'outline') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'divider';
      }
    | {
        /**
         * Optional heading for the timeline.
         */
        title?: string | null;
        /**
         * Chronological sequence of events or milestones.
         */
        items: {
          /**
           * Date or time label (e.g. “2018”, “March 2024”, “Day 3”).
           */
          date?: string | null;
          /**
           * Short title for this moment.
           */
          headline: string;
          description?: string | null;
          image?: (number | null) | Media;
          /**
           * Optional link to a related article or source.
           */
          link?: string | null;
          /**
           * Marks this moment as a key highlight.
           */
          highlight?: boolean | null;
          id?: string | null;
        }[];
        /**
         * Visual presentation hint for frontend rendering.
         */
        style?: ('vertical' | 'horizontal' | 'compact') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'timeline';
      }
  )[];
  aiRanking?: {
    boost?: number | null;
    decay?: number | null;
    freshness?: number | null;
    aiNotes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  parent?: (number | null) | Category;
  status: 'active' | 'hidden' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories".
 */
export interface Subcategory {
  id: number;
  name: string;
  slug: string;
  category: number | Category;
  status: 'active' | 'hidden';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Human-readable tag name (e.g. “Southern Soul”)
   */
  label: string;
  /**
   * Auto-generated URL-safe identifier
   */
  slug?: string | null;
  /**
   * Optional context for editors and AI classification
   */
  description?: string | null;
  /**
   * Used for trending tags, homepage features, or playlists
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-series".
 */
export interface ArticleSery {
  id: number;
  /**
   * Series title (e.g. “Justice Rides a White Horse”)
   */
  title: string;
  /**
   * Optional subtitle or theme line.
   */
  subtitle?: string | null;
  /**
   * URL-friendly identifier for the series.
   */
  slug: string;
  /**
   * Overview of the series purpose, scope, or narrative arc.
   */
  description?: string | null;
  status?: ('draft' | 'active' | 'completed' | 'archived') | null;
  /**
   * Feature this series on landing pages or homepage.
   */
  isFeatured?: boolean | null;
  hero?: {
    image?: (number | null) | Media;
    alt?: string | null;
    credit?: string | null;
  };
  /**
   * Articles included in this series, in reading order.
   */
  articles?:
    | {
        article: number | Article;
        /**
         * Reading order within the series (1, 2, 3…).
         */
        order: number;
        /**
         * Optional display label (e.g. “Part II”, “Chapter 3”).
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-calculated count of articles in this series.
   */
  totalArticles?: number | null;
  /**
   * Internal notes about the series direction, updates, or changes.
   */
  editorialNotes?:
    | {
        note: string;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radioShows".
 */
export interface RadioShow {
  id: number;
  title: string;
  slug?: string | null;
  showType: 'live' | 'recorded' | 'syndicated' | 'chart';
  hosts?: (number | Talent)[] | null;
  schedule?: {
    days?: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday')[] | null;
    startTime?: string | null;
    endTime?: string | null;
  };
  description?: string | null;
  genres?: ('rnb' | 'hip_hop' | 'southern_soul' | 'gospel' | 'talk' | 'culture' | 'news')[] | null;
  chart?: (number | null) | Chart;
  coverArt?: (number | null) | Media;
  isFeatured?: boolean | null;
  isPodcast?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "talent".
 */
export interface Talent {
  id: number;
  displayName: string;
  slug?: string | null;
  role: 'host' | 'dj' | 'producer' | 'contributor' | 'guest';
  bio?: string | null;
  photo?: (number | null) | Media;
  socials?: {
    instagram?: string | null;
    twitter?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
  };
  /**
   * Link to platform user account (optional)
   */
  user?: (number | null) | User;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "charts".
 */
export interface Chart {
  id: number;
  title: string;
  chartKey: 'hitlist' | 'rnb-soul' | 'hip-hop' | 'southern-soul' | 'gospel';
  chartMode: 'manual' | 'hybrid' | 'automated';
  /**
   * Optional playlist associated with this chart (editorial or promotional)
   */
  playlist?: (number | null) | Playlist;
  /**
   * Auto format: chartKey-week
   */
  slug?: string | null;
  status?: ('draft' | 'review' | 'published' | 'archived') | null;
  publishDate: string;
  /**
   * ISO week (e.g. 2026-W05)
   */
  week?: string | null;
  /**
   * Coverage range for this chart
   */
  weekRange: {
    startDate: string;
    endDate: string;
  };
  /**
   * Drag to reorder — rank auto-updates
   */
  entries: {
    rank?: number | null;
    movement?: ('up' | 'down' | 'same' | 'new') | null;
    manualTrack: {
      title: string;
      artist: string;
      isrc?: string | null;
      label?: string | null;
      releaseDate?: string | null;
    };
    trackTitle?: string | null;
    artist?: string | null;
    /**
     * Optional editorial score
     */
    score?: number | null;
    id?: string | null;
  }[];
  /**
   * Historical weekly snapshots
   */
  snapshots?:
    | {
        week?: string | null;
        weekRange?: {
          startDate?: string | null;
          endDate?: string | null;
        };
        entries?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playlists".
 */
export interface Playlist {
  id: number;
  title: string;
  slug?: string | null;
  playlistType: 'chart' | 'editorial' | 'creator' | 'sponsored';
  description?: string | null;
  tracks?:
    | {
        track: number | MediaTrack;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'published' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaTracks".
 */
export interface MediaTrack {
  id: number;
  title: string;
  slug?: string | null;
  primaryArtist: string;
  featuredArtists?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  releaseDate?: string | null;
  label?: string | null;
  isrc?: string | null;
  explicit?: boolean | null;
  genres?: ('rnb' | 'hip_hop' | 'southern_soul' | 'gospel' | 'talk' | 'culture' | 'news')[] | null;
  moods?: ('Chill' | 'Upbeat' | 'Late Night' | 'Inspirational' | 'Party' | 'Romantic' | 'Reflective')[] | null;
  audioFile?: (number | null) | Media;
  coverArt?: (number | null) | Media;
  rights?: {
    rightsHolder?: string | null;
    publishing?: string | null;
    territories?: string | null;
    expiryDate?: string | null;
  };
  source?: ('label' | 'creator' | 'internal') | null;
  creator?: (number | null) | User;
  isIndie?: boolean | null;
  isRadioApproved?: boolean | null;
  isChartEligible?: boolean | null;
  status?: ('draft' | 'review' | 'approved' | 'archived') | null;
  editorialNotes?: string | null;
  metrics?: {
    radioPlays?: number | null;
    streams?: number | null;
    listenerVotes?: number | null;
  };
  /**
   * Album this track belongs to.
   */
  album?: (number | null) | Album;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums".
 */
export interface Album {
  id: number;
  title: string;
  slug?: string | null;
  primaryArtist: string;
  featuredArtists?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  releaseDate?: string | null;
  label?: string | null;
  coverArt: number | Media;
  /**
   * Tracks associated with this album. You may manually add tracks or rely on auto-association.
   */
  tracks?: (number | MediaTrack)[] | null;
  /**
   * Optional manual track list for unreleased or external tracks.
   */
  manualTracks?:
    | {
        title: string;
        artist?: string | null;
        duration?: string | null;
        isExplicit?: boolean | null;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'published' | 'archived') | null;
  editorialNotes?: string | null;
  /**
   * Highlights this album in the homepage Featured Release slot.
   */
  isFeaturedRelease?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts".
 */
export interface Podcast {
  id: number;
  title: string;
  slug?: string | null;
  description?: string | null;
  hosts?: (number | Talent)[] | null;
  coverArt?: (number | null) | Media;
  distribution?: {
    applePodcasts?: boolean | null;
    spotify?: boolean | null;
    youtube?: boolean | null;
    wavenation?: boolean | null;
  };
  status?: ('draft' | 'active' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vod".
 */
export interface Vod {
  id: number;
  title: string;
  slug?: string | null;
  vodType: 'episode' | 'series' | 'film' | 'documentary' | 'clip' | 'liveReplay' | 'special';
  series?: (number | null) | Vod;
  season?: number | null;
  episodeNumber?: number | null;
  status?: ('draft' | 'review' | 'published' | 'archived') | null;
  visibility?: ('free' | 'premium' | 'ppv' | 'unlisted') | null;
  video: number | Media;
  poster?: (number | null) | Media;
  trailer?: (number | null) | Media;
  description?: string | null;
  runtime?: number | null;
  releaseDate?: string | null;
  genres?:
    | ('Music' | 'Talk' | 'Documentary' | 'Film' | 'Faith' | 'Culture' | 'News' | 'Lifestyle' | 'Comedy' | 'Southern')[]
    | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  source?: ('original' | 'creator' | 'partner' | 'event') | null;
  creator?: (number | null) | User;
  rights?: {
    rightsHolder?: string | null;
    territories?: string | null;
    expiryDate?: string | null;
  };
  pricing?: {
    price?: number | null;
    currency?: string | null;
  };
  isFeatured?: boolean | null;
  isTVEligible?: boolean | null;
  distribution?: {
    web?: boolean | null;
    mobile?: boolean | null;
    tv?: boolean | null;
  };
  metrics?: {
    views?: number | null;
    watchTime?: number | null;
    completionRate?: number | null;
  };
  publishDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "polls".
 */
export interface Poll {
  id: number;
  question: string;
  /**
   * Optional context shown under the poll question.
   */
  description?: string | null;
  /**
   * Each option must have a label and a stable slug.
   */
  options: {
    label: string;
    /**
     * Used internally for voting and results.
     */
    slug: string;
    id?: string | null;
  }[];
  status?: ('draft' | 'live' | 'closed') | null;
  featureOnHomepage?: boolean | null;
  /**
   * Optional. Leave blank to start immediately.
   */
  startDate?: string | null;
  /**
   * Optional. Poll auto-closes after this date.
   */
  endDate?: string | null;
  internalNotes?: string | null;
  context?: ('homepage' | 'chart' | 'show' | 'article') | null;
  relatedArticle?: (number | null) | Article;
  relatedShow?: (number | null) | RadioShow;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable weekly snapshots used for chart history, movement, and analytics.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chart-snapshots".
 */
export interface ChartSnapshot {
  id: number;
  chart: number | Chart;
  /**
   * ISO week or date range (e.g. 2026-W05)
   */
  week: string;
  label: string;
  entries: {
    rank: number;
    previousRank?: number | null;
    movement: 'up' | 'down' | 'new' | 'same';
    trackId: string;
    artist?: string | null;
    finalScore: number;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radioSchedule".
 */
export interface RadioSchedule {
  id: number;
  label: string;
  scheduleType: 'recurring' | 'oneTime' | 'special';
  radioShow: number | RadioShow;
  episode?: (number | null) | Episode;
  chart?: (number | null) | Chart;
  daysOfWeek?: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday')[] | null;
  startDate?: string | null;
  endDate?: string | null;
  startTime: string;
  endTime: string;
  priority?: number | null;
  overrideReason?: string | null;
  isLive?: boolean | null;
  isReplay?: boolean | null;
  isAutomation?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes".
 */
export interface Episode {
  id: number;
  title: string;
  slug?: string | null;
  episodeType: 'podcast' | 'radio' | 'special';
  podcast?: (number | null) | Podcast;
  radioShow?: (number | null) | RadioShow;
  audio: number | Media;
  hasVideo?: boolean | null;
  vod?: (number | null) | Vod;
  description?: string | null;
  duration?: number | null;
  hosts?: (number | Talent)[] | null;
  isExplicit?: boolean | null;
  isFeatured?: boolean | null;
  distribution?: {
    podcastPlatforms?: boolean | null;
    radioReplay?: boolean | null;
    web?: boolean | null;
    mobile?: boolean | null;
    tv?: boolean | null;
  };
  status?: ('draft' | 'published' | 'archived') | null;
  publishDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pollVotes".
 */
export interface PollVote {
  id: number;
  poll: number | Poll;
  option: string;
  ipHash: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-preferences';
        value: number | PayloadPreference;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'article-series';
        value: number | ArticleSery;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'subcategories';
        value: number | Subcategory;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'mediaTracks';
        value: number | MediaTrack;
      } | null)
    | ({
        relationTo: 'albums';
        value: number | Album;
      } | null)
    | ({
        relationTo: 'charts';
        value: number | Chart;
      } | null)
    | ({
        relationTo: 'chart-snapshots';
        value: number | ChartSnapshot;
      } | null)
    | ({
        relationTo: 'vod';
        value: number | Vod;
      } | null)
    | ({
        relationTo: 'radioShows';
        value: number | RadioShow;
      } | null)
    | ({
        relationTo: 'radioSchedule';
        value: number | RadioSchedule;
      } | null)
    | ({
        relationTo: 'podcasts';
        value: number | Podcast;
      } | null)
    | ({
        relationTo: 'episodes';
        value: number | Episode;
      } | null)
    | ({
        relationTo: 'playlists';
        value: number | Playlist;
      } | null)
    | ({
        relationTo: 'talent';
        value: number | Talent;
      } | null)
    | ({
        relationTo: 'polls';
        value: number | Poll;
      } | null)
    | ({
        relationTo: 'pollVotes';
        value: number | PollVote;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  displayName?: T;
  avatar?: T;
  subscription?: T;
  creatorProfile?:
    | T
    | {
        payoutEmail?: T;
        bio?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  slug?: T;
  categories?: T;
  subcategories?: T;
  tags?: T;
  publishDate?: T;
  scheduledPublishAt?: T;
  status?: T;
  reviewTier?: T;
  isBreaking?: T;
  isFeatured?: T;
  author?: T;
  editorPreset?: T;
  editorialNotes?:
    | T
    | {
        noteType?: T;
        note?: T;
        author?: T;
        createdAt?: T;
        id?: T;
      };
  excerpt?: T;
  sources?:
    | T
    | {
        sourceType?: T;
        title?: T;
        publication?: T;
        url?: T;
        author?: T;
        publishedDate?: T;
        isPrimary?: T;
        notes?: T;
        id?: T;
      };
  references?:
    | T
    | {
        label?: T;
        referenceType?: T;
        url?: T;
        notes?: T;
        id?: T;
      };
  series?: T;
  relatedShow?: T;
  relatedPosdcast?: T;
  relatedVOD?: T;
  relatedAlbum?: T;
  relatedPolls?: T;
  menuFeature?: T;
  menuContext?: T;
  menuEyebrow?: T;
  menuDescription?: T;
  readingTime?: T;
  hero?:
    | T
    | {
        image?: T;
        caption?: T;
        credit?: T;
      };
  contentBlocks?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        interviewQuestion?:
          | T
          | {
              question?: T;
              askedBy?: T;
              id?: T;
              blockName?: T;
            };
        interviewAnswer?:
          | T
          | {
              answer?: T;
              answeredBy?: T;
              highlight?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              credit?: T;
              fullWidth?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pullQuote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              provider?: T;
              url?: T;
              file?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        audio?:
          | T
          | {
              title?: T;
              audioFile?: T;
              showName?: T;
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              provider?: T;
              embedUrl?: T;
              id?: T;
              blockName?: T;
            };
        artistSpotlight?:
          | T
          | {
              artistName?: T;
              image?: T;
              description?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        relatedArticles?:
          | T
          | {
              articles?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              headline?: T;
              body?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    date?: T;
                    headline?: T;
                    description?: T;
                    image?: T;
                    link?: T;
                    highlight?: T;
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
      };
  aiRanking?:
    | T
    | {
        boost?: T;
        decay?: T;
        freshness?: T;
        aiNotes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-series_select".
 */
export interface ArticleSeriesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  slug?: T;
  description?: T;
  status?: T;
  isFeatured?: T;
  hero?:
    | T
    | {
        image?: T;
        alt?: T;
        credit?: T;
      };
  articles?:
    | T
    | {
        article?: T;
        order?: T;
        label?: T;
        id?: T;
      };
  totalArticles?: T;
  editorialNotes?:
    | T
    | {
        note?: T;
        createdAt?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories_select".
 */
export interface SubcategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  description?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaTracks_select".
 */
export interface MediaTracksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryArtist?: T;
  featuredArtists?:
    | T
    | {
        name?: T;
        id?: T;
      };
  releaseDate?: T;
  label?: T;
  isrc?: T;
  explicit?: T;
  genres?: T;
  moods?: T;
  audioFile?: T;
  coverArt?: T;
  rights?:
    | T
    | {
        rightsHolder?: T;
        publishing?: T;
        territories?: T;
        expiryDate?: T;
      };
  source?: T;
  creator?: T;
  isIndie?: T;
  isRadioApproved?: T;
  isChartEligible?: T;
  status?: T;
  editorialNotes?: T;
  metrics?:
    | T
    | {
        radioPlays?: T;
        streams?: T;
        listenerVotes?: T;
      };
  album?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums_select".
 */
export interface AlbumsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryArtist?: T;
  featuredArtists?:
    | T
    | {
        name?: T;
        id?: T;
      };
  releaseDate?: T;
  label?: T;
  coverArt?: T;
  tracks?: T;
  manualTracks?:
    | T
    | {
        title?: T;
        artist?: T;
        duration?: T;
        isExplicit?: T;
        id?: T;
      };
  status?: T;
  editorialNotes?: T;
  isFeaturedRelease?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "charts_select".
 */
export interface ChartsSelect<T extends boolean = true> {
  title?: T;
  chartKey?: T;
  chartMode?: T;
  playlist?: T;
  slug?: T;
  status?: T;
  publishDate?: T;
  week?: T;
  weekRange?:
    | T
    | {
        startDate?: T;
        endDate?: T;
      };
  entries?:
    | T
    | {
        rank?: T;
        movement?: T;
        manualTrack?:
          | T
          | {
              title?: T;
              artist?: T;
              isrc?: T;
              label?: T;
              releaseDate?: T;
            };
        trackTitle?: T;
        artist?: T;
        score?: T;
        id?: T;
      };
  snapshots?:
    | T
    | {
        week?: T;
        weekRange?:
          | T
          | {
              startDate?: T;
              endDate?: T;
            };
        entries?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chart-snapshots_select".
 */
export interface ChartSnapshotsSelect<T extends boolean = true> {
  chart?: T;
  week?: T;
  label?: T;
  entries?:
    | T
    | {
        rank?: T;
        previousRank?: T;
        movement?: T;
        trackId?: T;
        artist?: T;
        finalScore?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vod_select".
 */
export interface VodSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  vodType?: T;
  series?: T;
  season?: T;
  episodeNumber?: T;
  status?: T;
  visibility?: T;
  video?: T;
  poster?: T;
  trailer?: T;
  description?: T;
  runtime?: T;
  releaseDate?: T;
  genres?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  source?: T;
  creator?: T;
  rights?:
    | T
    | {
        rightsHolder?: T;
        territories?: T;
        expiryDate?: T;
      };
  pricing?:
    | T
    | {
        price?: T;
        currency?: T;
      };
  isFeatured?: T;
  isTVEligible?: T;
  distribution?:
    | T
    | {
        web?: T;
        mobile?: T;
        tv?: T;
      };
  metrics?:
    | T
    | {
        views?: T;
        watchTime?: T;
        completionRate?: T;
      };
  publishDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radioShows_select".
 */
export interface RadioShowsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  showType?: T;
  hosts?: T;
  schedule?:
    | T
    | {
        days?: T;
        startTime?: T;
        endTime?: T;
      };
  description?: T;
  genres?: T;
  chart?: T;
  coverArt?: T;
  isFeatured?: T;
  isPodcast?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "radioSchedule_select".
 */
export interface RadioScheduleSelect<T extends boolean = true> {
  label?: T;
  scheduleType?: T;
  radioShow?: T;
  episode?: T;
  chart?: T;
  daysOfWeek?: T;
  startDate?: T;
  endDate?: T;
  startTime?: T;
  endTime?: T;
  priority?: T;
  overrideReason?: T;
  isLive?: T;
  isReplay?: T;
  isAutomation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts_select".
 */
export interface PodcastsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  hosts?: T;
  coverArt?: T;
  distribution?:
    | T
    | {
        applePodcasts?: T;
        spotify?: T;
        youtube?: T;
        wavenation?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes_select".
 */
export interface EpisodesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  episodeType?: T;
  podcast?: T;
  radioShow?: T;
  audio?: T;
  hasVideo?: T;
  vod?: T;
  description?: T;
  duration?: T;
  hosts?: T;
  isExplicit?: T;
  isFeatured?: T;
  distribution?:
    | T
    | {
        podcastPlatforms?: T;
        radioReplay?: T;
        web?: T;
        mobile?: T;
        tv?: T;
      };
  status?: T;
  publishDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playlists_select".
 */
export interface PlaylistsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  playlistType?: T;
  description?: T;
  tracks?:
    | T
    | {
        track?: T;
        order?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "talent_select".
 */
export interface TalentSelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  role?: T;
  bio?: T;
  photo?: T;
  socials?:
    | T
    | {
        instagram?: T;
        twitter?: T;
        youtube?: T;
        tiktok?: T;
      };
  user?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "polls_select".
 */
export interface PollsSelect<T extends boolean = true> {
  question?: T;
  description?: T;
  options?:
    | T
    | {
        label?: T;
        slug?: T;
        id?: T;
      };
  status?: T;
  featureOnHomepage?: T;
  startDate?: T;
  endDate?: T;
  internalNotes?: T;
  context?: T;
  relatedArticle?: T;
  relatedShow?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pollVotes_select".
 */
export interface PollVotesSelect<T extends boolean = true> {
  poll?: T;
  option?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}